[BASIC.qushu]
host = "http://10.40.22.41/store/his/getstime?tagids="
header = { private-key = "0064b936562a4d14913b565fe9f6fb6f" }
start = "2025-08-01T00:00:00+08:00"                           # 东八区datetime
end = "2035-11-28T00:00:00+08:00"

[BASIC.line_info]
# 各产线基础信息
TR02 = { line_id = "101", line_name = "贵轮胎面二号线" }
SW01 = { line_id = "104", line_name = "贵轮胎侧一号线" }

[BASIC.db_info]
host = "10.40.22.41"
user = "root"
pwd = "jHWnhLxg^qPG+5FNalgk"
db = "smart_prod_line_v1"
rdbms = "mysql"

[BASIC.calculate]
prefix = ["front", "behind"]
indices = ["zl", "zk"]
suffix = ["op", "mc"]
batch_by = ["norm_name"]
filter = ["velocity", "status"]

[BASIC.limit]
zl = [0.03, 0.05, true]    # tolerace, valid, by_percentage
zk = [4, 10, false]
zk_large = [10, 15, false]

[BASIC.schema]
norm = "str"
zk_ = "f64"
zl_ = "f64"
velocity = "f64"
control = "bool"
status = "bool"


# [TR02]
# EXTP002001 = "前规格"     #挤出规格计划号
# EXTP002057 = "后规格"     # 裁断规格计划号
# EXTP002022 = "前重量"     #前连续秤重量
# EXTP002023 = "后重量"     #在线监测
# EXTP002061 = "联动线设定速度"
# EXTP002017 = "联动线实际速度"
# EXTP002037 = "上挤出机速度"  #上挤出机速度实际值(桂林苑)
# EXTP002059 = "智能使用"    #自动控制

[TAG.SW01]
EXTP001001 = "front_norm_name" # "前规格"
# EXTP000000 = "front_zl_standard" # 暂无标签
EXTP001002 = "front_zl_op" # "前操作侧重量"  # 连续称重量OP
EXTP001003 = "front_zl_mc" # "前驱动侧重量"  # 连续称重量MC
# EXTP000000 = "front_zk_standard" # 暂无标签
EXTP001004 = "front_zk_op"      # "前操作侧宽度"          # 前总宽1（操作侧）左
EXTP001005 = "front_zk_mc"      # "前驱动侧宽度"          # 前总宽2（驱动侧）右
EXTP001013 = "behind_norm_name" # "后规格"
# EXTP000000 = "behind_zl_standard"    # 暂无标签
# EXTP001065 = "behind_zl_op"          # 终选称op重量
# EXTP001066 = "behind_zl_mc"          # 终选称mc重量 
# EXTP001057 = "behind_zk_standard"    # "后宽度标准"  # 标签暂时有问题, 没有跟随后规格一起切换                
EXTP001047 = "behind_zk_op"          # "后操作侧宽度"
EXTP001048 = "behind_zk_mc"          # "后驱动侧宽度"
EXTP001051 = "line_velocity_set"     # "联动线设定速度"
EXTP001018 = "line_velocity_real"    # "联动线实际速度"               # 联动线实际值（收缩1实际）
EXTP001052 = "top_extruder_velocity" # "上挤出机速度"                
EXTP001055 = "control"               # "智能使用"                  # 手自动控制信号
EXTP001060 = "status"                # 设备运行状态
